# ---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.84.173
      ansible_user: centos
#lighthouse:
#  hosts:
#    lighthouse-01:
#      ansible_host: 84.201.134.103
#      ansible_user: centos
#vector:
#  hosts:
#    vector-01:
#      ansible_host: 84.201.129.29
#      ansible_user: centos
