---
  - name: clickhouse
    src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
  - name: lighthouse
    src: git@github.com:panarin0290/lighthouse-role.git
    scm: git
  - name: vector
    src: git@github.com:panarin0290/vector-role.git
    scm: git