---
- name: install nginx
  hosts: lighthouse
  handlers:
    - name: start-nginx
      become: true
      command: nginx
    - name: reload-nginx
      become: true
      command: nginx -s reload
  tasks:
    - name: NGINX | Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: NGINX | Install NGINX
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: start-nginx
    - name: NGINX | Create general config
      become: true
      # ansible.builtin.template:
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: reload-nginx
- name: Install lighthouse
  hosts: lighthouse
  handlers:
    - name: reload-nginx
      become: true
      command: nginx -s reload
  pre_tasks:
    - name: Lighthouse | install dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  tasks:
    - name: Lighthouse | Copy from git
      git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ lighthouse_location_dir }}"

    # - name: NGINX | Start
    #   ansible.builtin.command: "sudo service nginx start"


    - name: Lighthouse | Create lighthouse config
      become: true
      template:
        src: lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644
      notify: reload-nginx

- name: Install Clickhouse
  hosts: clickhouse
  # debugger: always
  # debugger: never
  # debugger: on_failed
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
          check_mode: false # отключаем проверку таски
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    # - name: Check file exist
    #   ansible.builtin.file:
    #     path: clickhouse-common-static-{{ clickhouse_version }}.rpm
    #   register: rc
    # msg: file is exist
    # ------------------
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
    - name: create templ file
      ansible.builtin.template:
        src: one.txt.j2
        mode: 0755
        dest: ./config
        backup: true

# -----------------------------
 - name: Install Vector
   hosts: vector

   handlers:
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: Install Vector
        state: restarted
   tasks:
     - name: Get vector distrib
       ansible.builtin.get_url:
         url: "https://packages.timber.io/vector/0.20.0/vector-0.20.0-1.x86_64.rpm"
         dest: "./vector-0.20.0-1.x86_64.rpm"
       # check_mode: true # включаем проверку таски
     - name: Install vector packages
       become: true
       ansible.builtin.yum:
         name:
           # - vector-0.23.0-1.x86_64.rpm
            - vector-0.20.0-1.x86_64.rpm
          state: present
       notify: Start Vector service

    # -------------------------------
  # ansible.builtin.debug:
  #   # msg: "{{ vector_version }}"
  # msg: "{{ vector_url }}"

#- name: Vector | install rpm
#  hosts: vector
#  tasks:
#    - name: install vector
#      become: true
#      ansible.builtin.yum:
#        name: "{{ vector_url }}"
#        state: present
#    - name: Vector | Template config
#      ansible.builtin.template:
#        src: vector.yml.j2
#        dest: vector.yml
#        mode: "0644"
#        # owner: {{ ansible_user_id }}
#        # group: {{ ansible_user_gid }}
#        owner: centos
#        group: centos
#        validate: vector validate --no-environment  --config-yaml %s
#    - name: Vector | creat systemd unit
#      become: true
#      ansible.builtin.template:
#        src: vector.service.j2
#        dest: /etc/systemd/system/vector.service
#        mode: "0644"
#        # owner: {{ ansible_user_id }}
#        # group: {{ ansible_user_gid }}
#        owner: centos
#        group: centos
#    - name: Vector | Start service
#      become: true
#      ansible.builtin.systemd:
#        name: vector
#        state: started
#        deamon_reload: true
## -----------------------------------








# sudo systemctl status vector

# https://packages.timber.io/vector/0.23.0/vector-0.23.0-x86_64-apple-darwin.tar.gz

# sudo systemctl stop firewalld.service
